import { Flex } from "@chakra-ui/react";
import Head from "next/head";
// import Image from "next/image";
import { data } from "../data/cards";
// import { CardProps } from "../interface/CardProps";
// import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import Card from "../components/Card";

// const Card = dynamic(() => import("../components/Card"), {
//   ssr: false,
// });

export default function Home() {
  const cards = data;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        backgroundColor="#1a258d9e"
        m="auto"
        maxW="8xl"
        minH="100vh"
        flexWrap="wrap"
        gap="1em"
        justifyContent="space-evenly"
        alignItems="center"
      >
        {cards.map((card) => (
          <Card {...card} key={card.id} />
        ))}
      </Flex>
    </div>
  );
}
